### ISSUE TITLE
Django manager get_queryset

### ISSUE THREAD

**Issue by Colleoni** [sligodave/django-keyvalue#1]
Hi,

thank you for your work. 
I just want to tell you that as far as I understand before django 1.8 both get_query_set and get_queryset methods of the manager class were available. Now, in django 1.8 only get_queryset is available. 
I think you may consider updating your keyvalue manager.

Thank you again

Best regards,
    Luca

**Comment by sligodave** [comment]
Hi Luca,

Thanks very much for highlighting the issue. I must confess to not having looked at this repository for a while and never thought of revisiting it. Having said that, I'm happy to keep it ticking over.

Thanks again!
Dave
